language: node_js
sudo: true

node_js:
  - stable

cache:
  directories:
    - $HOME/.composer

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true

before_install:
  - sudo add-apt-repository ppa:ondrej/php5-5.6 -y
  - sudo apt-get update
  - sudo apt-get install curl php5 -y
  - sudo apt-get install curl php5-cli git -y
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - sudo mv composer.phar /usr/local/bin/composer
  - composer

install:
  - npm install gulp -g
  - npm install
  - composer install

script:
  # Default gulp is configured to run coder, csslint and eslint.
  - gulp
