<?php

/**
 * @file
 * Custom module for Ismaili.
 */

/**
 * Implementation of hook_menu().
 */
function webform_custom_filter_menu() {
  $items = array();

  // A page to demonstrate theming form elements in a table.
  $items['admin/content/webform/filters'] = array(
    'title' => 'Webform Table ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_custom_filter_form_table_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implementation of hook_theme.
 */
// function webform_custom_filter_theme() {
//   return array(
//     'webform_custom_filter_form_table_form' => array(
//       // The renderable element is the form.
//       'render element' => 'form',
//     ),
//   );
// }

/**
 * Page Callback / Form Builder for the table form.
 */
function webform_custom_filter_form_table_form($form = array(), &$form_state) {

print 'aman';
$sql = 'SELECT * from webform_views_subscribe LIMIT 10' ;
$result = db_query($sql);

$row = array();
$rows = array();
// foreach($result as $results){
// $row = array($results->sid, $results->email, $results->first_name, $results->last_name,$results->age_range,$results->country);
//    $rows[] = $row;
// print_r($rows);
// }

  // if ($result) {
  //   while ($results = db_fetch_array($rows)) {
  //           // $options[$results->sid] = '';
 foreach($result as $results){
            $form[$results->sid]['email'] = array('#value' => $results->email);
            $form[$results->sid]['first_name'] = array('#value' => $results->first_name);
            $form[$results->sid]['last_name'] = array('#value' => $results->last_name);
             $form[$results->sid]['age_range'] = array('#value' => $results->age_range);
            $form[$results->sid]['country'] = array('#value' => $results->country);
    
    }
  // }

 // echo"<pre>"; print_r($form);die();

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
 
  // $form['#redirect'] = 'admin/content/webform/filters';
 
  return $form;
}



function webform_custom_filter_theme() {
  return array(
   'webform_custom_filter_form_table_form'=> array('arguments' => array('form' => NULL),),
  );
}
/**
 * Theme callback for the form table.
 */

function theme_webform_custom_filter_form_table_form($form , $form_state) {

$form = array_shift($form);
// echo"<pre>" ;print_r($form);die();
  $rows = array();
  foreach ($form as $form) {
    $row = array();
    // echo"<pre>" ;print_r($form);die();
    // if (isset($form[$key]->email)) {
 
      // $status = drupal_render($form['featured'][$key]);
      // $row[] = array('data' => $status, ‘class’ => ‘checkbox’);
 // $test = $form['email']['#value'];
 //      $row = array('data' => drupal_render($test)) .'';
      // $row[] = array('data' => drupal_render($form[$key]['first_name']));
      // $row[] = array('data' => drupal_render($form[$key]['last_name']));
      // $row[] = array('data' => drupal_render($form[$key]['country']));
$email = $form['email']['#value'];
$first_name = $form['first_name']['#value'];
$last_name = $form['last_name']['#value'];
$age_range = $form['age_range']['#value'];
$country = $form['country']['#value'];
$row[] = array($email,$first_name,$last_name,$age_range,$country);
    // }
 
      // $rows[] = $row;
      // $rows = array_shift($rows);
   print_r($email);die();
  }

  
 
  // Individual table headers.
  $header = array();
  // $header[] = array('data'  => t('Featured’), ‘class’ => ‘checkbox’);
  $header[] = t('Email');
  $header[] = t('First name');
  $header[] = t('Last Name');
  $header[] = t('Country');
 


$per_page = 5;
// Initialize the pager
$current_page = pager_default_initialize(count($rows), $per_page);
// Split your list into page sized chunks
$chunks = array_chunk($rows, $per_page, TRUE);
// Show the appropriate items from the list
$output = theme('table', array('header' => $header, 'rows' => $chunks[$current_page]));
// Show the pager
$output .= theme('pager', array('quantity',count($rows)));





// $output = theme('table', array('header' => $header,'rows' => $rows ));
  // return $output;

  // $output = theme(’table’, $header, $rows);
  $output .= drupal_render($form);
  return $output;
}




// function theme_webform_custom_filter_form_table(&$variables) {
//   print_r($variables);die();
//   // Get the userful values.
//   $form = $variables['form'];
//   $rows = $form['rows'];
//   $header = $form['#header'];

//   // Setup the structure to be rendered and returned.
//   $content = array(
//     '#theme' => 'table',
//     '#header' => $header,
//     '#rows' => array(),
//   );

//   // Traverse each row.  @see element_chidren().
//   foreach (element_children($rows) as $row_index) {
//     $row = array();
//     // Traverse each column in the row.  @see element_children().
//     foreach (element_children($rows[$row_index]) as $col_index) {
//       // Render the column form element.
//       $row[] = drupal_render($rows[$row_index][$col_index]);
//     }
//     // Add the row to the table.
//     $content['#rows'][] = $row;
//   }

//   // Redner the table and return.
//   return drupal_render($content);
// }
