<?php
/**
 * This template is used to assemble all nodes selected during newsletter
 * creation with Simplenews Content Selection.
 *
 * The following variables are available:
 *    - $toc Table of content, if it exists, as generated by the function
 *    theme_scs_toc() or your own.
 *    - $nodes Array of built selected nodes, ready to be outputed with the
 *    render() function.
 */
?>
<div id="newsletter">
  <?php if ($toc): ?>
    <div id="toc">
      <?php echo $toc; ?>
    </div>
  <?php endif;?>
  <?php $i=0;
  foreach ($group as $keys => $node): ?>
  <div class="title" style="font-weight:bold; font-size: 16px;">
  	<?php echo $keys. "<br />";?>
  </div>
  	<?php foreach ($node as $key => $value) { ?>
  		<div class="value">
  		<?php echo "<h2>" . $value[$i][0] . "</h2><br />";
  		echo $value[$i][1] . "<br />";
      if(!empty($value[$i][2]))
        echo "<strong>Projects:</strong> " . $value[$i][2] . "<br />";
      if(!empty($value[$i][3]))
        echo "<strong>Geography:</strong> " . $value[$i][3] . "<br /><hr />";
      ?>
  		</div>
  	<?php } ?>
    <?php //echo render($node)
     ?>
  <?php endforeach;?>
</div>
