<?php

/**
 * @file
 * Filedot customizations.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function scs_filedepot_theme_registry_alter(&$theme_registry) {
  $theme_registry['filedepot_filelisting']['template'] = drupal_get_path('module', 'scs_filedepot') . '/templates/filelisting-record';
  $theme_registry['filedepot_filedetail']['template'] = drupal_get_path('module', 'scs_filedepot') . '/templates/filedetail';
  $theme_registry['filedepot_main_page']['template'] = drupal_get_path('module', 'scs_filedepot') . '/templates/filedepot-mainpage';
  $theme_registry['filedepot_folderperms']['template'] = drupal_get_path('module', 'scs_filedepot') . '/templates/folderperms';
  $theme_registry['filedepot_activefolder']['template'] = drupal_get_path('module', 'scs_filedepot') . '/templates/activefolder';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function scs_filedepot_preprocess_filedepot_filelisting(&$variables) {
  // File view link.
  global $user;
  $query = db_select('filedepot_files', 'ff')
                  ->fields('ff')
                  ->condition('fid', $variables['listingrec']['fid']);
  $result = $query->execute();
  $row = $result->fetchAssoc();

  $variables['action3_link'] = l(t('View'), 'file/' . $row['drupal_fid']);
  if (in_array('Super admin', $user->roles) || in_array('Main admin', $user->roles) ) {
    $variables['action5_link'] = l(t('Delete'), 'file/' . $row['drupal_fid'] . '/delete', array(
      'query' => array(
        'destination' => 'filedepot',
      ),
    ));
  }
  $variables['action4_link'] = l(t('Mail'), 'filedepot/mail/' . $row['drupal_fid']);

  // Truncate file name to 15 characters.
  $file_name_parts = explode('.', $variables['file_name']);
  $variables['file_name'] = truncate_utf8($file_name_parts[0], 15, FALSE, TRUE) . '.' . $file_name_parts[1];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function scs_filedepot_preprocess_filedepot_folderperms(&$variables) {
  // Rename titles.
  $variables['LANG_uploaddirect'] = t('Upload');
  $variables['LANG_categoryadmin'] = t('Create/Edit Folder');
  $variables['LANG_directupload'] = t('Upload');
  $variables['LANG_admin'] = t('Create/Edit Folder');

  $variables['help_text'] = t('!required In order to enable %upload and %create_edit permissions make sure you have enabled %view_folder permission', array(
    '!required' => '<span>*</span>',
    '%upload' => t('Upload'),
    '%create_edit' => t('Create/Edit Folder'),
    '%view_folder' => t('View folder'),
  ));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function scs_filedepot_preprocess_filedepot_folderperm_rec(&$variables) {
  // We dont need to show them.
  unset($variables['upload_perm']);
  unset($variables['uploadver_perm']);
  unset($variables['approve_perm']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function scs_filedepot_preprocess_filedepot_main_page(&$variables) {
  global $user;
  if (user_access('access content')) {
    if (in_array('Super admin', $user->roles) || in_array('Main admin', $user->roles) ) {
      $variables['file_search'] = l(t('File search'), 'admin/content/file/search');
    }
    else {
      $variables['file_search'] = '';
    }
  }
  else {
    $variables['file_search'] = '';
  }
}

/**
 * Implements hook_menu_alter().
 */
function scs_filedepot_menu_alter(&$items) {
  $items['filedepot']['title'] = 'Useful Documents';
  $items['filedepot/folder/%']['title'] = 'Useful Documents';
}
