<?php

/**
 * @file
 *
 * @see nodequeue_rules.rules.inc
 */

/**
 * Event: Node added to a nodequeue.
 * Implements hook_nodequeue_add()
 */
function nodequeue_rules_nodequeue_add($sqid, $nid) {
  $subqueue = nodequeue_load_subqueue($sqid);
  $queue = nodequeue_load($subqueue->qid);
  $node = node_load($nid);
  rules_invoke_event('nodequeue_rules_event_add_node', $queue, $node);
}

/**
 * Event: Node removed from a nodequeue.
 * Implements hook_nodequeue_remove()
 */
function nodequeue_rules_nodequeue_remove($sqid, $nid) {
  $subqueue = nodequeue_load_subqueue($sqid);
  $queue = nodequeue_load($subqueue->qid);
  $node = node_load($nid);
  rules_invoke_event('nodequeue_rules_event_remove_node', $queue, $node);
}

/**
 * Event: Nodes changed places in the nodequeue
 * Implements hook_nodequeue_swap()
 */
function nodequeue_rules_nodequeue_save_subqueue_order_alter($sqid, $nids) {
  $subqueue = nodequeue_load_subqueue($sqid);
  $queue = nodequeue_load($subqueue->qid);
  $nodes = array();
  foreach ($nids as $data) {
    $nodes[] = node_load($data['nid']);
  }
  rules_invoke_event('nodequeue_rules_event_save_subqueue_order_alter', $queue, $nodes);
}
